version: '3.8'

services:
    backend:
        image: extender777/scrum-backend
        ports:
            - '6005:5000'
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://mongodb:27017/scrum
            - JWT_SECRET=${JWT_SECRET}
            - CLAUDE_KEY=${CLAUDE_KEY}
        restart: unless-stopped
        depends_on:
            - mongodb

    frontend:
        image: extender777/scrum-frontend
        environment:
            - NODE_ENV=production
            - REACT_APP_API_BASE_URL=http://backend:5000
        ports:
            - '8787:80'
        restart: unless-stopped
        depends_on:
            - backend

    mongodb:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped
        logging:
            driver: none

volumes:
    mongo-data:
